config/routes.rb
VcsRiskTool::Application.routes.draw do
  root 'welcome#index'

  devise_for :users

  resources :users do
	  resources :risks
	end

	resources :risks

	get '/about', to: 'welcome#about'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/bryanrite/cancancan/wiki/Defining-Abilities
  end
end

app/models/risk.rb
class Risk < ActiveRecord::Base
	validates :client, :project, presence: true
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :risks, dependent: :destroy
  accepts_nested_attributes_for :risks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(user)
    user_risks_path(:user_id => current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/risks_controller.rb
class RisksController < ApplicationController

	before_action :authenticate_user!

	#index, create, new, edit, show, update, destroy

	def index
		@risks = Risk.where(user_id: current_user.id)
	end

	def create
		@user = params[:user_id].blank? ? current_user : User.find(params[:user_id])
		@risk = @user.risks.create(params[:risk].permit!)
		#@risk = @user.risks.create(risk_params)

		if @risk.save
		 	redirect_to user_risk_path(@user,@risk)
		else
			redirect_to new_user_risk_path(@user), notice: "Client and Project must be filled."
		end
	end

	def new
		@risk = Risk.new
	end

	def edit
		@risk = Risk.find(params[:id])
	end

	def show
		@risk = Risk.find(params[:id])
	end

	def update
		@user = params[:user_id].blank? ? current_user : User.find(params[:user_id])
		@risk = Risk.find(params[:id])
		if @risk.update_attributes(params[:risk].permit!)
			redirect_to user_risks_path(@user)
		else
			redirect_to edit_user_risk_path(@user, @risk), notice: "Client and Project must be filled."
		end
	end

	def destroy
		@risk = Risk.find(params[:id])
		@risk.destroy
		redirect_to risks_path
	end

	private
		def risk_params
			params.permit(:t1a, :t1b)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/risks_helper.rb
module RisksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.haml
%hr
%footer
	%p.text-center &copy; 2014 Forest Carbon

app/views/layouts/_topnav.html.haml
.navbar.navbar-default{role: "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "VCS Risk Tool", root_path, :class => 'navbar-brand'
    .navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to "New Risk Calc", new_user_risk_path(:user_id => current_user.id)
          %li
            = link_to "My Risk Calcs", user_risks_path(:user_id => current_user.id)
          %li
            = link_to "About This App", '/about'
          %li
            = link_to 'Edit profile', edit_user_registration_path
          %li
            = link_to "Logout", destroy_user_session_path, :method => :delete
        - else
          %li
            = link_to "Login", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %meta{content: "", name: "description"}/
    %meta{content: "", name: "author"}/
    %title VCS Risk Tool

    = favicon_link_tag
    = csrf_meta_tags

    -#= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag    "application", media: "all"

  %body
    .container

      = render 'layouts/topnav'

      = yield

      = render 'layouts/footer'

    -#= javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "application"

app/views/risks/_form.html.haml
.row
	.col-sm-12
		.panel.panel-default
			.panel-heading Project Information
			.panel-body
				.row
					.col-sm-6
						.form-group
							%label{:for => "exampleInputEmail1"} Client
							= f.text_field(:client, :class => 'form-control', :placeholder => 'Enter client name')
					.col-sm-6
						.form-group
							%label{:for => "exampleInputPassword1"} Project Name
							= f.text_field(:project, :class => 'form-control', :placeholder => 'Enter project name')

.row
	.col-sm-12
		.panel.panel-default
			.panel-heading Risk Assessment Forms
			.panel-body
				/ %ul.nav.nav-pills
				/ 	%li.active
				/ 		%a{"data-toggle" => "pill", :href => "#table1"} Project Management
				/ 	%li
				/ 		%a{"data-toggle" => "pill", :href => "#table2"} Financial Viability
				/ 	%li
				/ 		%a{"data-toggle" => "pill", :href => "#table3"} Opportunity Cost
				/ 	%li
				/ 		%a{"data-toggle" => "pill", :href => "#table4"} Project Longevity
				/ 	%li
				/ 		%a{"data-toggle" => "pill", :href => "#table6"} Land Tenure
				/ 	%li
				/ 		%a{"data-toggle" => "pill", :href => "#table7"} Community Engagement
				/ 	%li
				/ 		%a{"data-toggle" => "pill", :href => "#table8"} Political Risk
				/ 	%li
				/ 		%a{"data-toggle" => "pill", :href => "#table10"} Natural Risks

				/ .tab-content
				%h3 Table 1 - Project Management
				%hr
				#table1= render :partial => 'table1', :locals => {:f => f}
				%h3 Table 2 - Financial Viability
				%hr
				#table2= render :partial => 'table2', :locals => {:f => f}
				%h3 Table 3 - Opportunity Cost
				%hr
				#table3= render :partial => 'table3', :locals => {:f => f}
				%h3 Table 4 - Project Longevity
				%hr
				#table4= render :partial => 'table4', :locals => {:f => f}
				%h3 Table 6 - Land Tenure
				%hr
				#table6= render :partial => 'table6', :locals => {:f => f}
				%h3 Table 7 - Community Engagement
				%hr
				#table7= render :partial => 'table7', :locals => {:f => f}
				%h3 Table 8 - Political Risk
				%hr
				#table8= render :partial => 'table8', :locals => {:f => f}
				%h3 Table 10 - Natural Risks
				%hr
				#table10= render :partial => 'table10', :locals => {:f => f}

.row
	.col-sm-12
		.panel.panel-default
			.panel-heading Risk Calculation Result
			.panel-body
				#table11= render :partial => 'table11form', :locals => {:f => f}

app/views/risks/_table1.html.haml
%table.table.table-bordered
  %tr
    %th{:colspan => "2"} Project Management
    %th Metric
    %th.th1 Project Score
  %tr
    %td a
    %td.l Species planted (where applicable) associated with more than 25% of stocks on which GHG credits have previously been issued are not native or proven to be adapted to the same or similar agro-ecological zones (s) in which the project is located.
    %td 2
    %td= f.check_box(:t1a, {}, "2", "0")
  %tr
    %td b
    %td.l Ongoing, enforcement to prevent encroachment by outside actors is required to protect, more than 50% of stocks on which GHG credits have previously been issued.
    %td 2
    %td= f.check_box(:t1b, {}, "2", "0")
  %tr
    %td c
    %td.l Management team does not include individuals with significant experience in all skills necessary to successful undetake all project activities (ie, any area of required experience is not covered by at least one individual with at least 5 years experience in the area.
    %td 2
    %td= f.check_box(:t1c, {}, "2", "0")
  %tr
    %td d
    %td.l Management team does not maintain a presence in the country or is located more than a day of travel from the project site, considering all parcels or polygons in the project area.
    %td 2
    %td= f.check_box(:t1d, {}, "2", "0")
  %tr
    %td e
    %td.l <b>Mitigation</b>: Management team includes individuals with significant experience in AFOLU project design and implementation, carbon acounting and reporting (eg, individuals who have successfully managed projects through validation, verification, and issuance of GHG credits) under the VCS program or other approved GHG programs.
    %td -2
    %td= f.check_box(:t1e, {}, "-2", "0")
  %tr
    %td f
    %td.l <b>Mitigation</b>: Adaptive management plan in place
    %td -2
    %td= f.check_box(:t1f, {}, "-2", "0")
  %tr
    %td.l{:colspan => "3"} Total Project management (PM) [as applicable, (a+b+c+d+e+f)]. Total may be less than zero.
    %td= f.text_field(:t1_pm_total, :readonly => 'readonly', :id => 'table1sum', :class => 'result')

app/views/risks/_table10b.html.haml
%table.table.table-bordered
	%tr
		%th Total Natural Risk
		%th.th1 Project Score
	%tr
		%td.l Total Internal Risk (PM + FV + OC + PL). Total may not be less than zero.
		%td= f.text_field(:t5_total_internal_risk, :readonly => 'readonly', :id => 't5_total_internal_risk', :class => 'result')

app/views/risks/_table11.html.haml
%table.table.table-bordered
	%tr
		%th Risk Category
		%th Maximum Allowable Risk
		%th Project Rating
	%tr
		%td.l Internal Risk (from Table 5)
		%td 35
		- if r.t5_total_internal_risk > 35
			%td.td-fail= r.t5_total_internal_risk
		- else
			%td.td-success= r.t5_total_internal_risk
	%tr
		%td.l External Risk (from Table 9)
		%td 20
		- if r.t9_total_external_risk > 20
			%td.td-fail= r.t9_total_external_risk
		- else
			%td.td-success= r.t9_total_external_risk
	%tr
		%td.l Natural Risk (from Table 10)
		%td 35
		- if r.t10_total_natural_risk > 35
			%td.td-fail= r.t10_total_natural_risk
		- else
			%td.td-success= r.t10_total_natural_risk
	%tr
		%td.l Overall Risk Rating (a + b + c)
		%td 60
		- if r.overall_risk_rating < 60
			%td.td-success= r.overall_risk_rating
		- else
			%td.td-fail= r.overall_risk_rating

app/views/risks/_table11form.html.haml
%table.table.table-bordered
	%tr
		%th Risk Category
		%th Maximum Allowable Risk
		%th Project Rating
	%tr
		%td.l Internal Risk (from Table 5)
		%td 35
		%td= f.text_field(:t5_total_internal_risk, :readonly => 'readonly', :class => 'result t5_total_internal_risk')
	%tr
		%td.l External Risk (from Table 9)
		%td 20
		%td= f.text_field(:t9_total_external_risk, :readonly => 'readonly', :class => 'result t9_total_external_risk')
	%tr
		%td.l Natural Risk (from Table 10)
		%td 35
		%td= f.text_field(:t10_total_natural_risk, :readonly => 'readonly', :class => 'result t10_total_natural_risk')
	%tr
		%td.l Overall Risk Rating (a + b + c)
		%td 90
		%td= f.text_field(:overall_risk_rating, :readonly => 'readonly', :class => 'result overall_risk_rating')

app/views/risks/_table2.html.haml
%table.table.table-bordered
  %tr
    %th{:colspan => "2"} Financial Viability
    %th Metric
    %th.th1 Project Score
  %tr
    %td a
    %td.l Project cashflow breakeven point is greater than 10 years from current risk assessment
    %td 3
    %td.group1= f.radio_button(:t2a_d, "3")
  %tr
    %td b
    %td.l Project cashflow breakeven point is between 7 and up to 10 years from current risk assessment
    %td 2
    %td.group1= f.radio_button(:t2a_d, "2")
  %tr
    %td c
    %td.l Project cashflow breakeven point is between 4 and up to 7 years from current risk assessment
    %td 1
    %td.group1= f.radio_button(:t2a_d, "1")
  %tr
    %td d
    %td.l Project cashflow breakeven point is 4 years or less from current risk assessment
    %td 0
    %td.group1= f.radio_button(:t2a_d, "0")
  %tr
    %td e
    %td.l Project has secured less than 15% of funding needed to cover the total cash out before the project reaches breakeven
    %td 3
    %td.group2= f.radio_button(:t2e_h, "3")
  %tr
    %td f
    %td.l Project has secured 15% to less than 40% of funding needed to cover the total cash out before the project reaches breakeven
    %td 2
    %td.group2= f.radio_button(:t2e_h, "2")
  %tr
    %td g
    %td.l Project has secured 40% to less than 80% of funding needed to cover the total cash out before the project reaches breakeven
    %td 1
    %td.group2= f.radio_button(:t2e_h, "1")
  %tr
    %td h
    %td.l Project has secured 80% or more of funding needed to cover the total cash out before the project reaches breakeven
    %td 0
    %td.group2= f.radio_button(:t2e_h, "0")
  %tr
    %td i
    %td.l <b>Mitigation</b>: Project has available as callable financial resources at least 50% of total cash out before project reaches breakeven.
    %td -2
    %td= f.check_box(:t2i, {}, "-2", "0")
  %tr
    %td.l{:colspan => "3"} Total Financial Viability (FV) [as applicable, ((a,,b, c or d) + (e, f, g or h) + i)]. Total may be less than zero.
    %td= f.text_field(:t2_fv_total, :readonly => 'readonly', :id => 'table2sum', :class => 'result')

app/views/risks/_table3.html.haml
%table.table.table-bordered
  %tr
    %th{:colspan => "2"} Opportunity Cost
    %th Metric
    %th.th1 Project Score
  %tr
    %td a
    %td.l NPV from the most profitable alternative land use activity is expected to be at least 100% more than that associated with project activities; or where baseline activities are subsistence driven, net positive community impacts are not demonstrated.
    %td 8
    %td.group1= f.radio_button(:t3a_f, "8")
  %tr
    %td b
    %td.l NPV from the most profitable alternative land use activity is expected to be between 50% and up to 100% mre than from project activities
    %td 6
    %td.group1= f.radio_button(:t3a_f, "6")
  %tr
    %td c
    %td.l NPV from the most profitable alternative land use activity is expected to be between 20% and up to 50% mre than from project activities
    %td 4
    %td.group1= f.radio_button(:t3a_f, "4")
  %tr
    %td d
    %td.l NPV from the most profitable alternative land use activity is expected to be between 20% more than and up to 20% less than from project activities; or where baseline activities are subsistence-driven, net positive community impacts are demonstrated.
    %td 0
    %td.group1= f.radio_button(:t3a_f, "0")
  %tr
    %td e
    %td.l NPV from project activities is expected to be between 20% and up to 50% more profitable than the most profitable alternative land use activity
    %td -2
    %td.group1= f.radio_button(:t3a_f, "-2")
  %tr
    %td f
    %td.l NPV from project activities is expected to be at least 50%,more profitable than the most profitable alternative land use activity.
    %td -4
    %td.group1= f.radio_button(:t3a_f, "-4")
  %tr
    %td g
    %td.l <b>Mitigation</b>: Project proponent is a non-profit organization
    %td -2
    %td.group2= f.radio_button(:t3g_i, "-2.01")
  %tr
    %td h
    %td.l <b>Mitigation</b>: Project is protected by legally binding commitment (see Section 2.2.4) to continue management practices that protect the credited carbon stocks over the length of the project crediting period.
    %td -2
    %td.group2= f.radio_button(:t3g_i, "-2.02")
  %tr
    %td i
    %td.l <b>Mitigation</b>: Project is protected by legally binding commitment (see Section 2.2.4) to continue management practices that protect the credited carbon stocks over at least 100 years.
    %td -8
    %td.group2= f.radio_button(:t3g_i, "-8")
  %tr
    %td.l{:colspan => "3"} Total Opportunity Cost (OC) [as applicable, (a, b, c, d, e or f) + (g or h) + i]. Total may be less than zero.
    %td= f.text_field(:t3_oc_total, :readonly => 'readonly', :id => 'table3sum', :class => 'result')

app/views/risks/_table4.html.haml
%table.table.table-bordered
  %tr
    %th{:colspan => "2"} Project Longevity
    %th Formula
    %th.th1 Years
  %tr
    %td.l{:colspan => "3"}
      This project follows the calculation as stated below:
    %td.group1= f.radio_button(:t4except, "0", :id => 'pl-normal')
  %tr
    %td a
    %td.l Without legal agreeement or requirement to continue the management practice.
    %td 24 - (project longevity<b>*</b>/5)
    %td= f.text_field(:t4_pl_a, :type => 'number')
  %tr
    %td b
    %td.l With legal agreeement or requirement to continue the management practice.
    %td 30 - (project longevity<b>*</b>/2)
    %td= f.text_field(:t4_pl_b, :type => 'number')
  %tr
    %td.l{:colspan => "3"}
      This project is with a legally binding agreement that covers at least a 100 year period from the project start date (PL score = Zero)
    %td.group1= f.radio_button(:t4except, "1", :id => 'pl-zero')
  %tr
    %td.l{:colspan => "3"}
      This AFOLU project longevity is less than 30 years, this project fails the risk assessment and is not eligible for crediting (Rating = Fail)
    %td.group1= f.radio_button(:t4except, "2", :id => 'pl-fail')
  %tr
    %td.l{:colspan => "3"}
      Total Project Longevity (PL). May not be less than zero.
      .pull-right
        .btn.btn-xs.btn-primary#table4calculatebutton Calculate
    %td= f.text_field(:t4_pl_value, :readonly => 'readonly', :id => 'table4sum', :class => 'result')

%p <b>*</b>Values are in years.

app/views/risks/_table5.html.haml
%table.table.table-bordered
	%tr
		%th Total Internal Risk
		%th.th1 Project Score
	%tr
		%td.l Total Internal Risk (PM + FV + OC + PL). Total may not be less than zero.
		%td= f.text_field(:t5_total_internal_risk, :readonly => 'readonly', :id => 't5_total_internal_risk', :class => 'result')

app/views/risks/_table8.html.haml
%table.table.table-bordered
  %tr
    %th{:colspan => "2"} Political Risk
    %th Metric
    %th.th1 Project Score
  %tr
    %td a
    %td.l Governance Score of less than -0.79
    %td 6
    %td.group1= f.radio_button(:t8a_e, "6")
  %tr
    %td b
    %td.l Governance Score of -0.79 to less than -0.32
    %td 4
    %td.group1= f.radio_button(:t8a_e, "4")
  %tr
    %td c
    %td.l Governance Score of -0.32 to less than 0.19
    %td 2
    %td.group1= f.radio_button(:t8a_e, "2")
  %tr
    %td d
    %td.l Governance Score of 0.19 to less than 0.82
    %td 1
    %td.group1= f.radio_button(:t8a_e, "1")
  %tr
    %td e
    %td.l Governance Score of -0.82 or higher
    %td 0
    %td.group1= f.radio_button(:t8a_e, "0")
  %tr
    %td f
    %td.l <b>Mitigation</b>: Country is implementing REDD+ Readiness or other activities, as set out in this section 2.3.3
    %td -2
    %td= f.check_box(:t8f, {}, "-2", "0")
  %tr
    %td.l{:colspan => "3"} Total Political (PC) [ as applicable ((a,b,c,d or e) + f)]. Total may not be less than zero.
    %td= f.text_field(:t8_pr_total, :readonly => 'readonly', :id => 'table8sum', :class => 'result')

app/views/risks/_table9.html.haml
%table.table.table-bordered
	%tr
		%th Total External Risk
		%th.th1 Project Score
	%tr
		%td.l Total External Risk (LT + CE + PC). Total may not be less than zero.
		%td= f.text_field(:t9_total_external_risk, :readonly => 'readonly', :id => 't9_total_external_risk', :class => 'result')

app/views/risks/edit.html.haml
= form_for @risk, method: :put do |f|
	= render :partial => 'form', :locals => {:f => f}
	= f.submit "Update Calculation", :class => 'btn btn-primary'

app/views/risks/index.html.haml
/ - if notice
/ 	.alert.alert-warning.alert-dismissable
/ 		%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
/ 		%strong= notice
- if @risks.exists?
	%h2 All Calculated Risks
	%hr
	%table.table.table-bordered
		%tr
			%th{:width => '20%'} Client
			%th{:width => '25%'} Project
			%th{:width => '15%'} Risk Rating
			%th{:width => '15%'} Status
			%th{:width => '15%'} Actions
		- @risks.each do |r|
			%tr
				%td.l= 	r.client
				%td.l= 	r.project
				%td= 		r.overall_risk_rating
				- if r.overall_risk_rating < 60
					%td.td-success Pass
				- else
					%td.td-fail Fail
				%td
					= link_to "Detail", user_risk_path(current_user.id,r.id), :class => 'btn btn-primary btn-xs'
					= link_to "Edit", edit_user_risk_path(current_user.id,r.id), :class => 'btn btn-success btn-xs'
					= link_to "Delete", user_risk_path(current_user.id,r.id), :class => 'btn btn-danger btn-xs', :method => :delete
- else
	%h2 No Risk Calculations.
	= link_to "Create New Risk Calc", new_risk_path, :class => 'btn btn-primary'

app/views/risks/show.html.haml
%h2 Calculated Risk Rating
%hr
	-#= render :partial => 'table5', :locals => {:r => @risk}
	-#= render :partial => 'table9', :locals => {:r => @risk}
	= render :partial => 'table11', :locals => {:r => @risk}
	= link_to "Edit", edit_user_risk_path(:user_id => current_user.id), :class => 'btn btn-success'
	= link_to "Delete", risk_path, :class => 'btn btn-danger', :method => :delete

app/views/welcome/about.html.haml
.row
	.col-sm-12
		%h2.text-center Hi There!
	.col-sm-4.col-sm-offset-2
		%h3 About Me
		%hr
		%p.text-center= image_tag 'pic.jpg', :class => 'img-circle', :width => '157px'
		%p.l I am a passionate web application and front-end developer in Jakarta. I have experience in HTML, CSS, JavaScript, and I make apps on Laravel and Ruby on Rails frameworks.
		%p.l I also work at <a href="http://forest-carbon.org">Forest Carbon</a> as IT and GIS/RS Specialist in forestry sector. I do imagery and other spatial data analysis, and conduct GIS trainings.
		%p
			= link_to 'Website', 'http://mahardhitama.com', :class => 'btn btn-primary btn-xs'
			= link_to 'LinkedIn', 'http://id.linkedin.com/in/prasetyams', :class => 'btn btn-primary btn-xs'
			= link_to 'Facebook', 'http://facebook.com/prsty', :class => 'btn btn-primary btn-xs'
	.col-sm-4
		%h3 About This App
		%hr
		%p.text-center= image_tag 'vine.jpg', :class => 'img-circle', :width => '157px'
		%p.l This app is made as a college assignment. This subject is selected as a helpful tool for project developers and funding committees in preparing or auditing AFOLU projects. This tool is an improvement to previous tool that was made with Microsoft Excel. This tool is far from perfect, and there are some UX bugs that need to be fixed in future releases.

app/views/welcome/index.html.haml
.jumbotron
	%h1 Welcome
	%p This tool provides the procedures for conducting the non-permanence risk analysis and buffer determination required for Agriculture Forestry and Other Land Use (AFOLU) projects. The tool sets out the requirements for project proponents, implementing partners and validation/verification bodies to assess risk and determine the appropriate risk rating.
	%p
		%a{:href => "http://www.v-c-s.org/program-documents/afolu-non-permanence-risk-tool-v32", :class => 'btn btn-success'} VCS Website
		- if user_signed_in?
			= link_to "New Risk Calc", new_user_risk_path(:user_id => current_user.id), :class => 'btn btn-primary'
		- else
			= link_to "Get Started", new_user_session_path, :class => 'btn btn-primary'